import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const golosText = localFont({
  src: [
    {
      path: './fonts/GolosText-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/GolosText-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-golos-text',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${golosText.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col font-sans">
        <Header />
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
